# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('type', models.IntegerField(choices=[(1, b'Font'), (2, b'Background'), (3, b'Material'), (4, b'Plate Type')], default=3, verbose_name='\u7c7b\u578b')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
    ]
