# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='download_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
