# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_download_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='download_url',
        ),
        migrations.AddField(
            model_name='material',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='\u5c01\u9762'),
        ),
    ]
