# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20170521_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.IntegerField(choices=[(1, b'\xe5\xad\x97\xe4\xbd\x93'), (2, b'\xe8\x83\x8c\xe6\x99\xaf'), (3, b'\xe7\x9f\xa2\xe9\x87\x8f'), (4, b'\xe7\x89\x88\xe5\xbc\x8f')], default=3, verbose_name='\u7c7b\u578b'),
        ),
    ]
