# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteobject',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materials.Material', verbose_name='\u7d20\u6750'),
        ),
    ]
